### ISSUE TITLE
panic: template: pattern matches no files: `templates/*`

### ISSUE THREAD

**Issue by denis-kisel** [rzane/docker2exe#1]
Hi, I try to use your converter, but there are some errors:

My Env:
Ubuntu 20.04

$ docker2exe --name my-app --image my-app:1.0

Output:
panic: template: pattern matches no files: `templates/*`

goroutine 1 [running]:
text/template.Must(0x0, 0x63bc40, 0xc00006a330, 0x63bc40)
	/Users/rzane/.asdf/installs/golang/1.13.6/go/src/text/template/helper.go:23 +0x54
github.com/rzane/docker2exe/cmd.init()
	/Users/rzane/Workspace/binny/cmd/generator.go:12 +0x58

**Comment by rzane** [comment]
Whoops! I'm a total go noob! This should be fixed in v0.2, though.
