### ISSUE TITLE
Exe build failed

### ISSUE THREAD

**Issue by kidharb** [rzane/docker2exe#3]
I am trying to convert clearlinux/tesseract-ocr:latest to an exe and this has failed with the below error.

uname -a
Linux pop-os 5.18.10-76051810-generic #202207071639~1659403207~22.04~cb5f582 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux

> ./docker2exe-linux-amd64 --name tesseract_docker --image clearlinux/tesseract-ocr:latest
> go mod init github.com/kidharb/tesseract_docker
> go: creating new go.mod: module github.com/kidharb/tesseract_docker
> go: to add module requirements and sums:
> 	go mod tidy
> go get
> go: added github.com/mattn/go-isatty v0.0.14
> go: added golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
> GOOS=darwin GOARCH=amd64 go build -o "/home/kidharb/src/docker_exe/dist/tesseract_docker-darwin-amd64"
> \# github.com/kidharb/tesseract_docker
> ./shim.go:61:9: cmd.Err undefined (type *exec.Cmd has no field or method Err)
> ./shim.go:62:14: cmd.Err undefined (type *exec.Cmd has no field or method Err)
> make: *** [Makefile:28: darwin/amd64] Error 2
> exit status 2
>

**Comment by kidharb** [comment]
I thought this utility does something else ie converts a docker container to a standalone executable binary, if it does, then please can you help me resolve the above error

**Comment by rzane** [comment]
This program expects you to have a recent go compiler available. It looks like you might be using an older go version.

The binary that this program creates is not a standalone binary. Instead, the resulting binary will basically just execute docker with the arguments that you provided.
