### ISSUE TITLE
Does this solution still require docker tools on the target machine? 

### ISSUE THREAD

**Issue by sixman9** [rzane/docker2exe#6]
Apologies appearing pedantic but, is this tool able to generate executables of whatever size, that do ***not*** require the end user to have either the tools nor knowledge of Docker (therefore self-contained executables)?

Also, this generated cross-platform targets, correct (I myself am on Mac)?

**Comment by appvoid** [comment]
Did it work for you?

**Comment by sixman9** [comment]
@appvoid Never made use of it, sorry - if you do use it, can you feed it back here, gracious, amigo!

**Comment by carljmosca** [comment]
It worked for me if Docker was running.

**Comment by rzane** [comment]
Yeah, this requires that the person running the executable has docker or podman running. The main idea is that it can "launch" a container with parameters that you encode.
